name: Criar item
description: Adicione um novo item
title: "Título"
body:
  - type: textarea
    id: description
    attributes:
      label: O que aconteceu?
      description: Diga-nos também, o que esperava que acontecesse?
      placeholder: Diga-nos o que vê!
    validations:
      required: true