name: Criar item
description: Adicione um novo item
title: "[TYPE]: "
body:
  - type: textarea
    id: description
    attributes:
      label: O que aconteceu?
      description: Diga-nos também, o que esperava que acontecesse?
      placeholder: Diga-nos o que vê!
      value: "Aconteceu um erro!"
    validations:
      required: true
  - type: textarea
    id: archives
    attributes:
      label: Arquivos
      description: Por favor, copie e cole qualquer saída de registo relevante. Isto será automaticamente formatado em código, pelo que não haverá necessidade de backticks.
      render: JSON